### ISSUE TITLE
CompileShaders gxdk requires the Microsoft Gaming SDK

### ISSUE THREAD

**Issue by Vict0r-Chen** [microsoft/Xbox-GDK-Samples#10]
I got this prompt when trying to compile [Xbox-GDK-Samples/Samples/System/Gamepad](https://github.com/microsoft/Xbox-GDK-Samples/tree/main/Samples/System/Gamepad) but I already have [GDK](https://github.com/microsoft/GDK/releases/tag/June_2021_Update_9) installed, I'm using visual studio 2019 and the debug platform is Gaming.Xbox.Xbox (x64), am I missing something?

**Comment by walbourn** [comment]
This is likely related to an environment variable it's trying to find. Does this issue still repro for you?

**Comment by walbourn** [comment]
If you only have the "Microsoft GDK" installed and *not* the "Microsoft GDK with Xbox extensions", then the ``CompileShaders gxdk`` command is going to fail. It is designed specifically for Gaming.Xbox.*.x64 platforms. You can build the ``Gaming.Desktop.x64`` platform with the "Microsoft GDK".
