### ISSUE TITLE
why GDK samples(console) exclude so many libs?

### ISSUE THREAD

**Issue by seocho3** [microsoft/Xbox-GDK-Samples#12]
$(IgnoreSpecificDefaultLibraries);advapi32.lib;comctl32.lib;comsupp.lib;dbghelp.lib;gdi32.lib;gdiplus.lib;guardcfw.lib;kernel32.lib;mmc.lib;msimg32.lib;msvcole.lib;msvcoled.lib;mswsock.lib;ntstrsafe.lib;ole2.lib;ole2autd.lib;ole2auto.lib;ole2d.lib;ole2ui.lib;ole2uid.lib;ole32.lib;oleacc.lib;oleaut32.lib;oledlg.lib;oledlgd.lib;oldnames.lib;runtimeobject.lib;shell32.lib;shlwapi.lib;strsafe.lib;urlmon.lib;user32.lib;userenv.lib;wlmole.lib;wlmoled.lib;onecore.lib;

they can not be used in Xbox console game development?

**Comment by walbourn** [comment]
The *Microsoft GDK with Xbox extensions* provides a specific [umbrella library](https://learn.microsoft.com/en-us/windows/win32/apiindex/windows-umbrella-libraries) ``xgameplatform.lib`` which provides all the Win32 API imports that are supported for the Xbox Game OS.

The list of ignore libraries avoids potential problems with 'mixing' umbrella libraries that have historically caused linker problems and exposed some unusual bugs as a result.

Note that ``/NODEFAULTLIB`` only works at suppressing ``#pragma comment(lib,"")`` statements. Explicit references to 'unsupported' libraries need to be removed from the build.
