### ISSUE TITLE
how to get open source lib used in Gaming.Xbox.Scarlett.x64 such as win32 libs using vcpkg?

### ISSUE THREAD

**Issue by seocho3** [microsoft/Xbox-GDK-Samples#13]
how to get open source lib used in Gaming.Xbox.Scarlett.x64 such as  win32 libs using vcpkg?
Is there a easy way or just porting by self?

**Comment by walbourn** [comment]
Can you tell us more about your scenario? What library?

**Comment by walbourn** [comment]
Note that there are now Xbox "community triplets" for VCPKG. 

https://walbourn.github.io/vcpkg-now-supports-targeting-xbox/

Keep in mind that without the GDKX, the linkage against `onecore_apiset.lib` used by these triplets will only work for core Win32 functions. The subset of USER32 present in `WINAPI_FAMILY_GAMES` will only link with the xgameplatform.lib in the GDKX.
