### ISSUE TITLE
Documentation for CMakeGDKExample is incorrect

### ISSUE THREAD

**Issue by djspringate** [microsoft/Xbox-GDK-Samples#17]
The sample appears to be written for a sample that uses Scarlett and XboxOne hardware too.
The presets for CMake have also changed.
The correct instructions to build this sample are as follows:

How to configure for VS2022:
Set generator to VS2022:
In CmakePresets.Json:
"generator": "Visual Studio 17 2022",
"XdkEditionTarget": "220602", (or whatever version you have installed)

How to build:
cd _(Xbox-GDK-Samples)_\Samples\Tools\CMakeGDKExample
cmake --preset=x64-Desktop
cmake --build out\build\x64-Desktop

The Visual Studio solution for the sample is now in _(Xbox-GDK-Samples)_\Samples\Tools\CMakeGDKExample\out\build\x64-Desktop !

**Comment by walbourn** [comment]
Thanks for the feedback.

All the notes you mention are in the currrent readme.docx, but I only show one of the three possible presets. I'll update it to be clearer about the PC usage.

**Comment by walbourn** [comment]
Note that the readme.docx will be empty unless you have git-LFS enabled.
