### ISSUE TITLE
m_gameInput->GetCurrentReading always returns 0x838a0003

### ISSUE THREAD

**Issue by luqiming666** [microsoft/Xbox-GDK-Samples#25]
Sample project: Gamepad or GamepadVibration
m_gameInput->GetCurrentReading always returns 0x838a0003. WHAT DOES IT MEAN?

There's no definition for this code in XGameErr.h.

I've connected a Xbox Controller Series X to my Win 11 PC for sure.

<img width="589" alt="no_controller_connected" src="https://user-images.githubusercontent.com/97005447/223092846-234d8670-ce46-45fb-9b80-31e3a882f588.png">

**Comment by walbourn** [comment]
That's "ERROR_PATH_NOT_FOUND".

Do you have the Game Runtime installed and the associated "GameInput" service running on the system?

**Comment by luqiming666** [comment]
I installed GDK-October_2022_Update_2. 
I just ran services.msc, and found that "GameInput Service" and "Gaming Services" were running...
Then I ran the sample codes agian. It works now :)

Thanks.
