### ISSUE TITLE
Is /s still valid for on GDK?

### ISSUE THREAD

**Issue by ZehCastro** [microsoft/Xbox-GDK-Samples#32]
https://github.com/microsoft/Xbox-GDK-Samples/blob/b5bbf45a6492cd706ca28ade7de7a95589a99229/Samples/Tools/CMakeExample/Scarlett/CMakeLists.txt#L209

**Comment by walbourn** [comment]
``/s`` is "optimize for SSD"

**Comment by walbourn** [comment]
Note that this option still exists, but it doesn't do anything anymore.
