### ISSUE TITLE
A 3rd-party gamepad to work with GameInput APIs?

### ISSUE THREAD

**Issue by luqiming666** [microsoft/Xbox-GDK-Samples#34]
As a gamepad device maker, I'm testing with GamepadVibration. How can I make our gamepad work with GameInput calls, specifically SetRumbleState() to make 4 motors vibrate? Do I need to go through some certification process with Microsoft? Thanks.

**Comment by walbourn** [comment]
The 4 motor vibration is part of the "GIP" spec used by Xbox One or later. You should contact the hardware partner program for more information.

https://www.xbox.com/en-US/designed-for-xbox
