### ISSUE TITLE
InGameStore.cpp UI samples

### ISSUE THREAD

**Issue by KyleBernelle** [microsoft/Xbox-GDK-Samples#35]
I'm in the middle of porting a game from the XDK to the GDK, and while working on the store functionality I noticed that the UIManager is included within the InGameStore samples. I also see XR-039 states "All purchases must use the Xbox console common purchase UI.".

Does the GDK handle the UI functionality in the use of the Xbox Series X store, or is this something that will actually need to be included within our own InGameStore files? Specifically, in UpdateProductList() I see some calls that use the UIManager, but in the MakePurchase() function there is the call to XStoreShowPurchaseUIResult, and ShowPopup. Which of these two are the aforementioned "Xbox console common purchase UI"?

**Comment by timch-ms** [comment]
UIManager is simply part of an internal UI framework we use for our samples. XStoreShowPurchaseUIAsync is what you will call to invoke the expected console purchase UI. This would be equivalent to the XDK's ShowPurchaseAsync.

**Comment by KyleBernelle** [comment]
Thank you very much for the swift reply! That is good-to-hear info!
