### ISSUE TITLE
how should use GDK for achievement?

### ISSUE THREAD

**Issue by ZCOREP** [microsoft/Xbox-GDK-Samples#43]
Hello, i have a unity game , and i get ID@Xbox , and i want add Xbox Achievement to my game,
i download this GDK and its c++! not c#!
how should i use it in unity for unlock Achievements?
thanks

**Comment by walbourn** [comment]
See https://github.com/microsoft/gdk-unity-package

https://forum.unity.com/threads/unity-and-microsoft-announce-the-microsoft-gdk-packages-for-unity-for-unity-2021-and-2022-lts.1590543/#post-9817860

**Comment by ZCOREP** [comment]
Thanks, but I think something is not correct. When I tried to build my game as UWP, I was getting a bunch of errors! I want to publish my game on Xbox, not for PC. The links you sent to me are just for PC, not Xbox.

**Comment by walbourn** [comment]
To use 'DevMode' on Xbox with Unity you just need a x64 UWP. I believe that is covered here:

https://docs.unity3d.com/Manual/uwp-environment-setup.html

There are some various quirks about the UWP on Xbox model:

https://walbourn.github.io/directx-and-uwp-on-xbox-series-x-s/

https://walbourn.github.io/directx-and-uwp-on-xbox-one/

**Comment by ZCOREP** [comment]
i know how should i use DevMode !!!!!!!!!
i want use GDK for Xbox...
i want unlock achievements with it.
