### ISSUE TITLE
Errors in Sample::AddUserWithUI

### ISSUE THREAD

**Issue by OZ1** [microsoft/Xbox-GDK-Samples#9]
XUserHandle user hides variable from the outer scope:
https://github.com/microsoft/Xbox-GDK-Samples/blob/e4d83410b150dbd2d9981f8cbafea530e9cfc4ec/Samples/Live/Fundamentals_Desktop/Fundamentals_Desktop.cpp#L177

resolveAsyncBlock is not used. asyncBlockInner should be replaced to resolveAsyncBlock at #L192 and #L196

I guess deleting asyncBlockInner at #L201 leads to deleting it one more time at L#206

**Comment by walbourn** [comment]
I believe this warning was fixed some time ago. Let us know if it still repros for you.
